# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install build dependencies
RUN apk add --no-cache build-base

WORKDIR /app

# Copy project files
COPY . .

# Install project dependencies
RUN pip install --upgrade pip \
    && pip install .

# Create dummy config and opml files if they do not exist
RUN test -f config.yaml || echo "# Default config" > config.yaml
RUN test -f feeds.opml || echo "<opml></opml>" > feeds.opml

# Expose port if necessary (not required for stdio transport)

CMD ["rssmcp", "--config", "config.yaml", "--opml", "feeds.opml"]
